import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Canvas } from "@react-three/fiber";

export default function Home() {
  return (
    <>
      <Head>
        <title>Raphaël Bosi's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Canvas
          shadows={true}
          className={styles.canvas}
          camera={{
            position: [10, 10, 10],
          }}
        >
          <ambientLight intensity={1} />
          <directionalLight color="red" position={[0, 0, 5]} />
          <mesh recieveShadow={true}>
            <boxBufferGeometry args={[10, 10, 10]} />
            <meshStandardMaterial color="white" />
          </mesh>
        </Canvas>
      </main>
    </>
  );
}
